dist: trusty

script: skip

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull python:3-slim

deploy:
  provider: script
  script: ./deploy.sh slidesdotcom2pdf
  on:
    branch: master

